### ISSUE TITLE
v0.0.1 TODO feature

### ISSUE THREAD

**Issue by teitei-tk** [teitei-tk/juiz#5]
# Goal
- [ ] ChatOpsAdapter(Slack,  Discord, etc)
- [x] Github API package
  * https://github.com/teitei-tk/juiz/tree/master/packages/github
- [ ] team pacakges with Github Org Teams
- [ ] assign PullRequest
